### PR TITLE
[drone] making both the version 1.0.0 and 0.8.6 available and creating soft link to latest

### PR DESCRIPTION
**Pull request by prabdeb**
Thanks @dcwangmit01 ! I have now addressed the comments in https://github.com/cisco-sso/kdk/pull/107

I need to release it as drone CLI is broken in latest `KDK`

### CODE REVIEW

**Comment by prabdeb** [comment]
@darkyat yes I thought of that initially but as @dcwangmit01 suggested currently we are doing the similar practice for all the other apps like helm, kubectl, etc. I did it in the same way!

**Comment by darkyat** [comment]
> @darkyat yes I thought of that initially but as @dcwangmit01 suggested currently we are doing the similar practice for all the other apps like helm, kubectl, etc. I did it in the same way!

I see. Fine for me then.

**Comment by marsavela** [comment]
@prabdeb is there any ETA for updating the server for this to stop being an issue?

**Comment by prabdeb** [comment]
@marsavela No not yet, Drone haven't released the 1.0.0 to Open Source community yet!

**Comment by dcwangmit01** [comment]
Thanks @prabdeb

**Pull request merged**
