### PR TITLE
Remove deprecated 1.9.2 kops and add 1.11.0

### PR DESCRIPTION
**Pull request by marsavela**
This PR removes old deprecated kops version and adds the latest stable version.

### CODE REVIEW

**Comment by dcwangmit01** [comment]
Nice PR.

We leave the newest major version in the KDK, up to 2 versions for kops.  Why?  Every version of kops deploys its own nodeup which tries to force to its binary images to the latest versions.

Thus if you've deployed a cluster using Kops 1.10.  Then, if you run Kops 1.11 without any config changes, it wants to rolling deploy/rebuild all of your nodes.  Therefore, it is handy to keep old versions around for a while.

Moving to Kops 1.11 right now, will require a rolling upgrade on ALL of your existing clusters, even if there are no configuration changes.

I would recommend modifying this PR to keep up to 2 older versions of kops.

**Comment by dcwangmit01** [comment]
Also, we're not sure if Kops 1.11 can successfully deploy Kube 1.12+, as we have been able to use Kops 1.10 to do so.  Before we remove 1.10, let's make sure that path works.

**Comment by dcwangmit01** [comment]
I do think this PR is merge-able

**Comment by marsavela** [comment]
@dcwangmit01 let me know if you want me to add 1.9.2 back in.

**Pull request merged**
